### ISSUE TITLE
Case study issues

### ISSUE THREAD

**Issue by A-Tawfik** [ObjectiveSubject/obsub#61]
**city of oakland**

- [x] brochure image= make into full width container with color matching light green

- [x] delete both beta.oak… and design.oak… links

- [x] delete We continue to support the City as it improves the quality of its visual communication.

**BPS**

- [x] poster image= make into full width container with color matching light blue

**NYCDOE**

- [x] English with a capital in pullout quote
- [ ] DOE-kickball = no border (David to supply)
/Users/davidjg/Dropbox (Objective Subject)/Current Projects/Objective Subject/OS Web/2016/Design/Image Assets/DOE/DOE-kickball.jpg
/Users/davidjg/Dropbox (Objective Subject)/Current Projects/Objective Subject/OS Web/2016/Design/Image Assets/DOE/DOE-kickball@2x-80.jpg

**ATIL**

- [x] logo to white on dark sections
- [x] spacing off for caption
- [ ] video to MP4

**HESTER**

- [x] logo to white on dark sections
- [ ] website screenshots cropped (David to supply) *all here*
<img width="425" alt="hs-graphics" src="https://user-images.githubusercontent.com/1825143/38705687-66afd190-3e78-11e8-8a77-6c87522dd0a2.png">

**GIBNEY**

- [ ]  back to top button
     - [x]  FIX SVG GRAPHIC on Safari
     - [ ]  show only on scroll up
     - [ ]  right align with grid margin on mobile
     - [x]  add videos **REEL** <iframe src="https://player.vimeo.com/video/264336408" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
     - [x]  add videos **MISSION** <iframe src="https://player.vimeo.com/video/264336135" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

- [x]  WAVY GRAPHIC = CENTER ALIGN

- [x]  Captions:

- [x] Caption this image #1
=
DELETE

- [x] CAPTION THIS IMAGE #4-5-6-7
=
Moments of the new website.

- [x] CAPTION THIS IMAGE #8-9-10
=
We developed a range of design fidelity to allow impactful material to be professionally designed, but also simpler design that can be accomplished by administrative staff, in-house.

**CGU**

- [x] customer journey to fit within grid

- [ ] switch school graphics (David to supply)

**Comment by jalbertgagnier** [comment]
@kpettinga can you take a look at these? GIBNEY section is most pressing (SVG, insert videos)
